name: "web_app"
mode: "dev"
port: 8080
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_backups: 7
  max_age: 30
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "1231"
  dbname: "bluebell"
  max_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

